      SUBROUTINE SMATRIX3(P,ANS)
C     
C     Generated by MadGraph5_aMC@NLO v. 3.4.1, 2022-09-01
C     By the MadGraph5_aMC@NLO Development Team
C     Visit launchpad.net/madgraph5 and amcatnlo.web.cern.ch
C     
C     MadGraph5_aMC@NLO for Madevent Version
C     
C     Returns amplitude squared summed/avg over colors
C     and helicities
C     for the point in phase space P(0:3,NEXTERNAL)
C     
C     Process: u~ u~ > u u~ u~ u~ WEIGHTED<=4
C     Process: c~ c~ > c c~ c~ c~ WEIGHTED<=4
C     Process: d~ d~ > d d~ d~ d~ WEIGHTED<=4
C     Process: s~ s~ > s s~ s~ s~ WEIGHTED<=4
C     
      IMPLICIT NONE
C     
C     CONSTANTS
C     
      Include 'genps.inc'
      Include 'maxconfigs.inc'
      Include 'nexternal.inc'
      Include 'maxamps.inc'
      INTEGER                 NCOMB         
      PARAMETER (             NCOMB=20)
      INTEGER    NGRAPHS
      PARAMETER (NGRAPHS=42) 
      INTEGER    NDIAGS
      PARAMETER (NDIAGS=42) 
      INTEGER    THEL
      PARAMETER (THEL=2*NCOMB)
C     
C     ARGUMENTS 
C     
      REAL*8 P(0:3,NEXTERNAL),ANS
C     
C     LOCAL VARIABLES 
C     
      INTEGER CONFSUB(MAXSPROC,LMAXCONFIGS)
      INCLUDE 'config_subproc_map.inc'
      INTEGER NHEL(NEXTERNAL,NCOMB)
      REAL*8 T
      REAL*8 R,SUMHEL,TS(NCOMB)
      INTEGER I,IDEN
      INTEGER JC(NEXTERNAL),II
      REAL*8 XTOT
      INTEGER  J, JJ

      double precision get_channel_cut
      external get_channel_cut

C     
C     GLOBAL VARIABLES
C     
      DOUBLE PRECISION AMP2(MAXAMPS), JAMP2(0:MAXFLOW)
      COMMON/TO_AMPS/  AMP2,       JAMP2


C     
C     INFORMATION TO WRITE THE HELICITY IN THE EVENT --not memory
C      efficient--
C     
      CHARACTER*101         HEL_BUFF
      COMMON/TO_HELICITY/  HEL_BUFF

      INTEGER NB_SPIN_STATE_in(2)
      common /nb_hel_state/ nb_spin_state_in

      REAL*8 POL(2)

      COMMON/TO_POLARIZATION/ POL
      double precision tmin_for_channel
      integer sde_strat   ! 1 means standard single diagram enhancement strategy,
C     2 means approximation by the	denominator of the propagator
      common/TO_CHANNEL_STRAT/tmin_for_channel,	sde_strat

      INTEGER          ISUM_HEL
      LOGICAL                    MULTI_CHANNEL
      COMMON/TO_MATRIX/ISUM_HEL, MULTI_CHANNEL
      INTEGER MAPCONFIG(0:LMAXCONFIGS), ICONFIG
      COMMON/TO_MCONFIGS/MAPCONFIG, ICONFIG
      INTEGER SUBDIAG(MAXSPROC),IB(2)
      COMMON/TO_SUB_DIAG/SUBDIAG,IB
      
      DATA (NHEL(I,1),I=1,6) /-1,-1,-1, 1,-1,-1/
      DATA (NHEL(I,2),I=1,6) /-1,-1,-1,-1, 1,-1/
      DATA (NHEL(I,3),I=1,6) /-1,-1,-1,-1,-1, 1/
      DATA (NHEL(I,4),I=1,6) /-1,-1, 1,-1,-1,-1/
      DATA (NHEL(I,5),I=1,6) /-1, 1,-1, 1, 1,-1/
      DATA (NHEL(I,6),I=1,6) /-1, 1,-1, 1,-1, 1/
      DATA (NHEL(I,7),I=1,6) /-1, 1,-1,-1, 1, 1/
      DATA (NHEL(I,8),I=1,6) /-1, 1, 1, 1,-1,-1/
      DATA (NHEL(I,9),I=1,6) /-1, 1, 1,-1, 1,-1/
      DATA (NHEL(I,10),I=1,6) /-1, 1, 1,-1,-1, 1/
      DATA (NHEL(I,11),I=1,6) / 1,-1,-1, 1, 1,-1/
      DATA (NHEL(I,12),I=1,6) / 1,-1,-1, 1,-1, 1/
      DATA (NHEL(I,13),I=1,6) / 1,-1,-1,-1, 1, 1/
      DATA (NHEL(I,14),I=1,6) / 1,-1, 1, 1,-1,-1/
      DATA (NHEL(I,15),I=1,6) / 1,-1, 1,-1, 1,-1/
      DATA (NHEL(I,16),I=1,6) / 1,-1, 1,-1,-1, 1/
      DATA (NHEL(I,17),I=1,6) / 1, 1,-1, 1, 1, 1/
      DATA (NHEL(I,18),I=1,6) / 1, 1, 1, 1, 1,-1/
      DATA (NHEL(I,19),I=1,6) / 1, 1, 1, 1,-1, 1/
      DATA (NHEL(I,20),I=1,6) / 1, 1, 1,-1, 1, 1/
      DATA IDEN/216/

C     ----------
C     BEGIN CODE
C     ----------

      DO I=1,NEXTERNAL
        JC(I) = +1
      ENDDO

      IF (multi_channel) THEN
        DO I=1,NDIAGS
          AMP2(I)=0D0
        ENDDO
        JAMP2(0)=6
        DO I=1,INT(JAMP2(0))
          JAMP2(I)=0D0
        ENDDO
      ENDIF
      ANS = 0D0
      WRITE(HEL_BUFF,'(20I5)') (0,I=1,NEXTERNAL)
C     Kiran please check if you need this:    
      DO I=1,NCOMB
        TS(I)=0d0
      ENDDO

      call MATRIX3(P ,JC(1), TS)
      DO I=1,NCOMB     
        T=TS(I)  
        DO JJ=1,nincoming
          IF(POL(JJ).NE.1d0.AND.NHEL(JJ,I).EQ.INT(SIGN(1d0,POL(JJ))))
     $      THEN
            T=T*ABS(POL(JJ))*NB_SPIN_STATE_IN(JJ)/2d0   ! NB_SPIN_STATE(JJ)/2d0 is added for polarised beam
          ELSE IF(POL(JJ).NE.1d0)THEN
            T=T*(2d0-ABS(POL(JJ)))*NB_SPIN_STATE_IN(JJ)/2d0
          ENDIF
        ENDDO
        ANS=ANS+DABS(T)
        TS(I)=T
      ENDDO

      IF (ANS.ne.0d0) THEN
        CALL RANMAR(R)
        SUMHEL=0d0
        DO I=1,NCOMB
          SUMHEL=SUMHEL+DABS(TS(I))/ANS
          IF(R.LT.SUMHEL)THEN
            WRITE(HEL_BUFF,'(20i5)')(NHEL(II,I),II=1,NEXTERNAL)
C           Set right sign for ANS, based on sign of chosen helicity
            ANS=DSIGN(ANS,TS(I))
            GOTO 10
          ENDIF
        ENDDO
 10     CONTINUE   
      ENDIF
      IF (MULTI_CHANNEL) THEN
        XTOT=0D0
        DO I=1,LMAXCONFIGS
          J = CONFSUB(3, I)
          if (J.ne.0)then
            if (sde_strat.eq.1)then
              AMP2(J) = AMP2(J) * GET_CHANNEL_CUT(P, I)
            else
              AMP2(J) = GET_CHANNEL_CUT(P, I)
            endif
            XTOT=XTOT+AMP2(J)

          endif
        ENDDO
        IF (XTOT.NE.0D0) THEN
          ANS=ANS*AMP2(SUBDIAG(3))/XTOT
        ELSE IF(ANS.ne.0d0) THEN
          write(*,*) 'Problem in the multi-channeling. All amp2 are'
     $     //' zero but not the total matrix-element'
          stop 1
        ENDIF
      ENDIF
      ANS=ANS/DBLE(IDEN)
      END


      Subroutine  MATRIX3(P,IC, TS)
C     
C     Generated by MadGraph5_aMC@NLO v. 3.4.1, 2022-09-01
C     By the MadGraph5_aMC@NLO Development Team
C     Visit launchpad.net/madgraph5 and amcatnlo.web.cern.ch
C     
C     Returns amplitude squared summed/avg over colors
C     for the point with external lines W(0:6,NEXTERNAL)
C     
C     Process: u~ u~ > u u~ u~ u~ WEIGHTED<=4
C     Process: c~ c~ > c c~ c~ c~ WEIGHTED<=4
C     Process: d~ d~ > d d~ d~ d~ WEIGHTED<=4
C     Process: s~ s~ > s s~ s~ s~ WEIGHTED<=4
C     
      IMPLICIT NONE
C     
C     CONSTANTS
C     
      INTEGER    NGRAPHS
      PARAMETER (NGRAPHS=42) 
      include 'genps.inc'
      include 'nexternal.inc'
      include 'maxamps.inc'
      INTEGER    NWAVEFUNCS,     NCOLOR
      PARAMETER (NWAVEFUNCS=192, NCOLOR=6) 
      REAL*8     ZERO
      PARAMETER (ZERO=0D0)
      COMPLEX*16 IMAG1
      PARAMETER (IMAG1=(0D0,1D0))
      INTEGER NAMPSO, NSQAMPSO
      PARAMETER (NAMPSO=1, NSQAMPSO=1)
      LOGICAL CHOSEN_SO_CONFIGS(NSQAMPSO)
      DATA CHOSEN_SO_CONFIGS/.TRUE./
      SAVE CHOSEN_SO_CONFIGS
      INTEGER                 NCOMB         
      PARAMETER (             NCOMB=20)
C     
C     ARGUMENTS 
C     
      REAL*8 P(0:3,NEXTERNAL)
      INTEGER NHEL(NEXTERNAL), IC(NEXTERNAL)
      REAL*8 TS(NCOMB)
C     
C     LOCAL VARIABLES 
C     
      INTEGER I,J,M,N,K
      COMPLEX*16 ZTEMP,TMP_JAMP(52)
      COMPLEX*16 TMP(6)
      REAL*8 CF(NCOLOR,NCOLOR)
      COMPLEX*16 AMP(NCOMB,NGRAPHS), JAMP(NCOLOR,NAMPSO)
      COMPLEX*16 W(6,NWAVEFUNCS)
C     Needed for v4 models
      COMPLEX*16 DUM0,DUM1
      DATA DUM0, DUM1/(0d0, 0d0), (1d0, 0d0)/

      double precision fk_ZERO 
      save fk_ZERO 

      logical first
      data first /.true./
      save first
C     
C     FUNCTION
C     
      INTEGER SQSOINDEX3

C     
C     GLOBAL VARIABLES
C     
      Double Precision amp2(maxamps), jamp2(0:maxflow)
      common/to_amps/  amp2,       jamp2
      include 'coupl.inc'

      double precision tmin_for_channel
      integer sde_strat   ! 1 means standard single diagram enhancement strategy,
C     2 means approximation by the	denominator of the propagator
      common/TO_CHANNEL_STRAT/tmin_for_channel,	sde_strat

      double precision small_width_treatment
      common/narrow_width/small_width_treatment
C     
C     COLOR DATA
C     
      DATA (CF(i,  1),i=  1,  6) /2.700000000000000d+01
     $ ,9.000000000000000d+00,9.000000000000000d+00,3.000000000000000d
     $ +00,3.000000000000000d+00,9.000000000000000d+00/
C     1 T(1,4) T(2,5) T(3,6)
      DATA (CF(i,  2),i=  1,  6) /9.000000000000000d+00
     $ ,2.700000000000000d+01,3.000000000000000d+00,9.000000000000000d
     $ +00,9.000000000000000d+00,3.000000000000000d+00/
C     1 T(1,4) T(2,6) T(3,5)
      DATA (CF(i,  3),i=  1,  6) /9.000000000000000d+00
     $ ,3.000000000000000d+00,2.700000000000000d+01,9.000000000000000d
     $ +00,9.000000000000000d+00,3.000000000000000d+00/
C     1 T(1,5) T(2,4) T(3,6)
      DATA (CF(i,  4),i=  1,  6) /3.000000000000000d+00
     $ ,9.000000000000000d+00,9.000000000000000d+00,2.700000000000000d
     $ +01,3.000000000000000d+00,9.000000000000000d+00/
C     1 T(1,5) T(2,6) T(3,4)
      DATA (CF(i,  5),i=  1,  6) /3.000000000000000d+00
     $ ,9.000000000000000d+00,9.000000000000000d+00,3.000000000000000d
     $ +00,2.700000000000000d+01,9.000000000000000d+00/
C     1 T(1,6) T(2,4) T(3,5)
      DATA (CF(i,  6),i=  1,  6) /9.000000000000000d+00
     $ ,3.000000000000000d+00,3.000000000000000d+00,9.000000000000000d
     $ +00,9.000000000000000d+00,2.700000000000000d+01/
C     1 T(1,6) T(2,5) T(3,4)
C     ----------
C     BEGIN CODE
C     ----------
      if (first) then
        first=.false.
        IF(ZERO.ne.0d0) fk_ZERO = SIGN(MAX(ABS(ZERO), ABS(ZERO
     $   *small_width_treatment)), ZERO)
      endif
      AMP(:,:) = (0d0,0d0)
            CALL OXXXXX(P(0,1),ZERO,+1,-1*IC(1),W(1,1)) ! count 39
      CALL OXXXXX(P(0,1),ZERO,-1,-1*IC(1),W(1,2)) ! count 39
      CALL OXXXXX(P(0,2),ZERO,+1,-1*IC(2),W(1,3)) ! count 39
      CALL OXXXXX(P(0,2),ZERO,-1,-1*IC(2),W(1,4)) ! count 39
      CALL OXXXXX(P(0,3),ZERO,+1,+1*IC(3),W(1,5)) ! count 39
      CALL OXXXXX(P(0,3),ZERO,-1,+1*IC(3),W(1,6)) ! count 39
      CALL IXXXXX(P(0,4),ZERO,+1,-1*IC(4),W(1,7)) ! count 15
      CALL IXXXXX(P(0,4),ZERO,-1,-1*IC(4),W(1,8)) ! count 15
      CALL IXXXXX(P(0,5),ZERO,+1,-1*IC(5),W(1,9)) ! count 33
      CALL IXXXXX(P(0,5),ZERO,-1,-1*IC(5),W(1,10)) ! count 33
      CALL IXXXXX(P(0,6),ZERO,+1,-1*IC(6),W(1,11)) ! count 33
      CALL IXXXXX(P(0,6),ZERO,-1,-1*IC(6),W(1,12)) ! count 33
      CALL FFV1P0_3(W(1,7),W(1,1),GC_11,ZERO,FK_ZERO,W(1,13)) ! count 16
      CALL FFV1P0_3(W(1,8),W(1,2),GC_11,ZERO,FK_ZERO,W(1,16)) ! count 16
      CALL FFV1P0_3(W(1,9),W(1,3),GC_11,ZERO,FK_ZERO,W(1,17)) ! count 34
      CALL FFV1P0_3(W(1,10),W(1,4),GC_11,ZERO,FK_ZERO,W(1,20)) ! count 34
      CALL FFV1_1(W(1,5),W(1,13),GC_11,ZERO,FK_ZERO,W(1,21)) ! count 4
      CALL FFV1_1(W(1,5),W(1,16),GC_11,ZERO,FK_ZERO,W(1,24)) ! count 4
      CALL FFV1_1(W(1,6),W(1,13),GC_11,ZERO,FK_ZERO,W(1,25)) ! count 4
      CALL FFV1_1(W(1,6),W(1,16),GC_11,ZERO,FK_ZERO,W(1,28)) ! count 4
      CALL FFV1P1N_2(W(1,11), W(1,17), GC_11, TMP(1))
      call CombineAmp(2,
     & (/17,7/), 
     & (/25,28/),
     & TMP, W, AMP(1,1))
      CALL FFV1P1N_2(W(1,11), W(1,20), GC_11, TMP(1))
      call CombineAmp(2,
     & (/12,3/), 
     & (/25,28/),
     & TMP, W, AMP(1,1))
      CALL FFV1P1N_2(W(1,12), W(1,17), GC_11, TMP(1))
      call CombineAmp(2,
     & (/18,9/), 
     & (/21,24/),
     & TMP, W, AMP(1,1))
      CALL FFV1P1N_2(W(1,12), W(1,20), GC_11, TMP(1))
      call CombineAmp(2,
     & (/14,4/), 
     & (/21,24/),
     & TMP, W, AMP(1,1)) ! count 1
      CALL FFV1_2(W(1,11),W(1,13),GC_11,ZERO,FK_ZERO,W(1,29)) ! count 4
      CALL FFV1_2(W(1,11),W(1,16),GC_11,ZERO,FK_ZERO,W(1,32)) ! count 4
      CALL FFV1_2(W(1,12),W(1,13),GC_11,ZERO,FK_ZERO,W(1,33)) ! count 4
      CALL FFV1_2(W(1,12),W(1,16),GC_11,ZERO,FK_ZERO,W(1,36)) ! count 4
      CALL FFV1P1N_1(W(1,6), W(1,17), GC_11, TMP(1))
      call CombineAmp(2,
     & (/17,7/), 
     & (/29,32/),
     & TMP, W, AMP(1,2))
      CALL FFV1P1N_1(W(1,6), W(1,20), GC_11, TMP(1))
      call CombineAmp(2,
     & (/12,3/), 
     & (/29,32/),
     & TMP, W, AMP(1,2))
      CALL FFV1P1N_1(W(1,5), W(1,17), GC_11, TMP(1))
      call CombineAmp(2,
     & (/18,9/), 
     & (/33,36/),
     & TMP, W, AMP(1,2))
      CALL FFV1P1N_1(W(1,5), W(1,20), GC_11, TMP(1))
      call CombineAmp(2,
     & (/14,4/), 
     & (/33,36/),
     & TMP, W, AMP(1,2)) ! count 1
      CALL FFV1P0_3(W(1,11),W(1,6),GC_11,ZERO,FK_ZERO,W(1,38)) ! count 34
      CALL FFV1P0_3(W(1,12),W(1,5),GC_11,ZERO,FK_ZERO,W(1,39)) ! count 34
      CALL VVV1P1N_1(W(1,17), W(1,38), GC_10, TMP(1))
      call CombineAmp(2,
     & (/17,7/), 
     & (/13,16/),
     & TMP, W, AMP(1,3))
      CALL VVV1P1N_1(W(1,17), W(1,39), GC_10, TMP(1))
      call CombineAmp(2,
     & (/18,9/), 
     & (/13,16/),
     & TMP, W, AMP(1,3))
      CALL VVV1P1N_1(W(1,20), W(1,38), GC_10, TMP(1))
      call CombineAmp(2,
     & (/12,3/), 
     & (/13,16/),
     & TMP, W, AMP(1,3))
      CALL VVV1P1N_1(W(1,20), W(1,39), GC_10, TMP(1))
      call CombineAmp(2,
     & (/14,4/), 
     & (/13,16/),
     & TMP, W, AMP(1,3)) ! count 1
      CALL FFV1P0_3(W(1,9),W(1,6),GC_11,ZERO,FK_ZERO,W(1,42)) ! count 34
      CALL FFV1P0_3(W(1,10),W(1,5),GC_11,ZERO,FK_ZERO,W(1,43)) ! count 34
      CALL FFV1_1(W(1,3),W(1,13),GC_11,ZERO,FK_ZERO,W(1,45)) ! count 4
      CALL FFV1_1(W(1,3),W(1,16),GC_11,ZERO,FK_ZERO,W(1,48)) ! count 4
      CALL FFV1_1(W(1,4),W(1,13),GC_11,ZERO,FK_ZERO,W(1,49)) ! count 4
      CALL FFV1_1(W(1,4),W(1,16),GC_11,ZERO,FK_ZERO,W(1,52)) ! count 4
      CALL FFV1P1N_2(W(1,11), W(1,42), GC_11, TMP(1))
      call CombineAmp(2,
     & (/17,7/), 
     & (/45,48/),
     & TMP, W, AMP(1,4))
      CALL FFV1P1N_2(W(1,11), W(1,43), GC_11, TMP(1))
      call CombineAmp(2,
     & (/19,10/), 
     & (/45,48/),
     & TMP, W, AMP(1,4))
      CALL FFV1P1N_2(W(1,12), W(1,42), GC_11, TMP(1))
      call CombineAmp(2,
     & (/11,2/), 
     & (/49,52/),
     & TMP, W, AMP(1,4))
      CALL FFV1P1N_2(W(1,12), W(1,43), GC_11, TMP(1))
      call CombineAmp(2,
     & (/14,4/), 
     & (/49,52/),
     & TMP, W, AMP(1,4)) ! count 1
      CALL FFV1P1N_1(W(1,3), W(1,42), GC_11, TMP(1))
      call CombineAmp(2,
     & (/17,7/), 
     & (/29,32/),
     & TMP, W, AMP(1,5))
      CALL FFV1P1N_1(W(1,3), W(1,43), GC_11, TMP(1))
      call CombineAmp(2,
     & (/19,10/), 
     & (/29,32/),
     & TMP, W, AMP(1,5))
      CALL FFV1P1N_1(W(1,4), W(1,42), GC_11, TMP(1))
      call CombineAmp(2,
     & (/11,2/), 
     & (/33,36/),
     & TMP, W, AMP(1,5))
      CALL FFV1P1N_1(W(1,4), W(1,43), GC_11, TMP(1))
      call CombineAmp(2,
     & (/14,4/), 
     & (/33,36/),
     & TMP, W, AMP(1,5)) ! count 1
      CALL FFV1P0_3(W(1,11),W(1,3),GC_11,ZERO,FK_ZERO,W(1,53)) ! count 34
      CALL FFV1P0_3(W(1,12),W(1,4),GC_11,ZERO,FK_ZERO,W(1,56)) ! count 34
      CALL VVV1P1N_1(W(1,42), W(1,53), GC_10, TMP(1))
      call CombineAmp(2,
     & (/17,7/), 
     & (/13,16/),
     & TMP, W, AMP(1,6))
      CALL VVV1P1N_1(W(1,42), W(1,56), GC_10, TMP(1))
      call CombineAmp(2,
     & (/11,2/), 
     & (/13,16/),
     & TMP, W, AMP(1,6))
      CALL VVV1P1N_1(W(1,43), W(1,53), GC_10, TMP(1))
      call CombineAmp(2,
     & (/19,10/), 
     & (/13,16/),
     & TMP, W, AMP(1,6))
      CALL VVV1P1N_1(W(1,43), W(1,56), GC_10, TMP(1))
      call CombineAmp(2,
     & (/14,4/), 
     & (/13,16/),
     & TMP, W, AMP(1,6)) ! count 1
      CALL FFV1_2(W(1,9),W(1,13),GC_11,ZERO,FK_ZERO,W(1,57)) ! count 4
      CALL FFV1_2(W(1,9),W(1,16),GC_11,ZERO,FK_ZERO,W(1,60)) ! count 4
      CALL FFV1_2(W(1,10),W(1,13),GC_11,ZERO,FK_ZERO,W(1,61)) ! count 4
      CALL FFV1_2(W(1,10),W(1,16),GC_11,ZERO,FK_ZERO,W(1,64)) ! count 4
      CALL FFV1P1N_1(W(1,6), W(1,53), GC_11, TMP(1))
      call CombineAmp(2,
     & (/17,7/), 
     & (/57,60/),
     & TMP, W, AMP(1,7))
      CALL FFV1P1N_1(W(1,6), W(1,56), GC_11, TMP(1))
      call CombineAmp(2,
     & (/11,2/), 
     & (/57,60/),
     & TMP, W, AMP(1,7))
      CALL FFV1P1N_1(W(1,5), W(1,53), GC_11, TMP(1))
      call CombineAmp(2,
     & (/19,10/), 
     & (/61,64/),
     & TMP, W, AMP(1,7))
      CALL FFV1P1N_1(W(1,5), W(1,56), GC_11, TMP(1))
      call CombineAmp(2,
     & (/14,4/), 
     & (/61,64/),
     & TMP, W, AMP(1,7)) ! count 1
      CALL FFV1P1N_2(W(1,9), W(1,53), GC_11, TMP(1))
      call CombineAmp(2,
     & (/17,7/), 
     & (/25,28/),
     & TMP, W, AMP(1,8))
      CALL FFV1P1N_2(W(1,9), W(1,56), GC_11, TMP(1))
      call CombineAmp(2,
     & (/11,2/), 
     & (/25,28/),
     & TMP, W, AMP(1,8))
      CALL FFV1P1N_2(W(1,10), W(1,53), GC_11, TMP(1))
      call CombineAmp(2,
     & (/19,10/), 
     & (/21,24/),
     & TMP, W, AMP(1,8))
      CALL FFV1P1N_2(W(1,10), W(1,56), GC_11, TMP(1))
      call CombineAmp(2,
     & (/14,4/), 
     & (/21,24/),
     & TMP, W, AMP(1,8)) ! count 1
      CALL FFV1P1N_1(W(1,3), W(1,38), GC_11, TMP(1))
      call CombineAmp(2,
     & (/17,7/), 
     & (/57,60/),
     & TMP, W, AMP(1,9))
      CALL FFV1P1N_1(W(1,3), W(1,39), GC_11, TMP(1))
      call CombineAmp(2,
     & (/18,9/), 
     & (/57,60/),
     & TMP, W, AMP(1,9))
      CALL FFV1P1N_1(W(1,4), W(1,38), GC_11, TMP(1))
      call CombineAmp(2,
     & (/12,3/), 
     & (/61,64/),
     & TMP, W, AMP(1,9))
      CALL FFV1P1N_1(W(1,4), W(1,39), GC_11, TMP(1))
      call CombineAmp(2,
     & (/14,4/), 
     & (/61,64/),
     & TMP, W, AMP(1,9)) ! count 1
      CALL FFV1P1N_2(W(1,9), W(1,38), GC_11, TMP(1))
      call CombineAmp(2,
     & (/17,7/), 
     & (/45,48/),
     & TMP, W, AMP(1,10))
      CALL FFV1P1N_2(W(1,9), W(1,39), GC_11, TMP(1))
      call CombineAmp(2,
     & (/18,9/), 
     & (/45,48/),
     & TMP, W, AMP(1,10))
      CALL FFV1P1N_2(W(1,10), W(1,38), GC_11, TMP(1))
      call CombineAmp(2,
     & (/12,3/), 
     & (/49,52/),
     & TMP, W, AMP(1,10))
      CALL FFV1P1N_2(W(1,10), W(1,39), GC_11, TMP(1))
      call CombineAmp(2,
     & (/14,4/), 
     & (/49,52/),
     & TMP, W, AMP(1,10)) ! count 1
      CALL FFV1P0_3(W(1,7),W(1,3),GC_11,ZERO,FK_ZERO,W(1,65)) ! count 16
      CALL FFV1P0_3(W(1,8),W(1,4),GC_11,ZERO,FK_ZERO,W(1,68)) ! count 16
      CALL FFV1P0_3(W(1,9),W(1,1),GC_11,ZERO,FK_ZERO,W(1,69)) ! count 34
      CALL FFV1P0_3(W(1,10),W(1,2),GC_11,ZERO,FK_ZERO,W(1,72)) ! count 34
      CALL FFV1_1(W(1,5),W(1,65),GC_11,ZERO,FK_ZERO,W(1,73)) ! count 4
      CALL FFV1_1(W(1,5),W(1,68),GC_11,ZERO,FK_ZERO,W(1,76)) ! count 4
      CALL FFV1_1(W(1,6),W(1,65),GC_11,ZERO,FK_ZERO,W(1,77)) ! count 4
      CALL FFV1_1(W(1,6),W(1,68),GC_11,ZERO,FK_ZERO,W(1,80)) ! count 4
      CALL FFV1P1N_2(W(1,11), W(1,69), GC_11, TMP(1))
      call CombineAmp(2,
     & (/17,13/), 
     & (/77,80/),
     & TMP, W, AMP(1,11))
      CALL FFV1P1N_2(W(1,11), W(1,72), GC_11, TMP(1))
      call CombineAmp(2,
     & (/6,3/), 
     & (/77,80/),
     & TMP, W, AMP(1,11))
      CALL FFV1P1N_2(W(1,12), W(1,69), GC_11, TMP(1))
      call CombineAmp(2,
     & (/18,15/), 
     & (/73,76/),
     & TMP, W, AMP(1,11))
      CALL FFV1P1N_2(W(1,12), W(1,72), GC_11, TMP(1))
      call CombineAmp(2,
     & (/8,4/), 
     & (/73,76/),
     & TMP, W, AMP(1,11)) ! count 1
      CALL FFV1_2(W(1,11),W(1,65),GC_11,ZERO,FK_ZERO,W(1,81)) ! count 4
      CALL FFV1_2(W(1,11),W(1,68),GC_11,ZERO,FK_ZERO,W(1,84)) ! count 4
      CALL FFV1_2(W(1,12),W(1,65),GC_11,ZERO,FK_ZERO,W(1,85)) ! count 4
      CALL FFV1_2(W(1,12),W(1,68),GC_11,ZERO,FK_ZERO,W(1,88)) ! count 4
      CALL FFV1P1N_1(W(1,6), W(1,69), GC_11, TMP(1))
      call CombineAmp(2,
     & (/17,13/), 
     & (/81,84/),
     & TMP, W, AMP(1,12))
      CALL FFV1P1N_1(W(1,6), W(1,72), GC_11, TMP(1))
      call CombineAmp(2,
     & (/6,3/), 
     & (/81,84/),
     & TMP, W, AMP(1,12))
      CALL FFV1P1N_1(W(1,5), W(1,69), GC_11, TMP(1))
      call CombineAmp(2,
     & (/18,15/), 
     & (/85,88/),
     & TMP, W, AMP(1,12))
      CALL FFV1P1N_1(W(1,5), W(1,72), GC_11, TMP(1))
      call CombineAmp(2,
     & (/8,4/), 
     & (/85,88/),
     & TMP, W, AMP(1,12)) ! count 1
      CALL VVV1P1N_1(W(1,69), W(1,38), GC_10, TMP(1))
      call CombineAmp(2,
     & (/17,13/), 
     & (/65,68/),
     & TMP, W, AMP(1,13))
      CALL VVV1P1N_1(W(1,69), W(1,39), GC_10, TMP(1))
      call CombineAmp(2,
     & (/18,15/), 
     & (/65,68/),
     & TMP, W, AMP(1,13))
      CALL VVV1P1N_1(W(1,72), W(1,38), GC_10, TMP(1))
      call CombineAmp(2,
     & (/6,3/), 
     & (/65,68/),
     & TMP, W, AMP(1,13))
      CALL VVV1P1N_1(W(1,72), W(1,39), GC_10, TMP(1))
      call CombineAmp(2,
     & (/8,4/), 
     & (/65,68/),
     & TMP, W, AMP(1,13)) ! count 1
      CALL FFV1_1(W(1,1),W(1,65),GC_11,ZERO,FK_ZERO,W(1,89)) ! count 4
      CALL FFV1_1(W(1,1),W(1,68),GC_11,ZERO,FK_ZERO,W(1,92)) ! count 4
      CALL FFV1_1(W(1,2),W(1,65),GC_11,ZERO,FK_ZERO,W(1,93)) ! count 4
      CALL FFV1_1(W(1,2),W(1,68),GC_11,ZERO,FK_ZERO,W(1,96)) ! count 4
      CALL FFV1P1N_2(W(1,11), W(1,42), GC_11, TMP(1))
      call CombineAmp(2,
     & (/17,13/), 
     & (/89,92/),
     & TMP, W, AMP(1,14))
      CALL FFV1P1N_2(W(1,11), W(1,43), GC_11, TMP(1))
      call CombineAmp(2,
     & (/19,16/), 
     & (/89,92/),
     & TMP, W, AMP(1,14))
      CALL FFV1P1N_2(W(1,12), W(1,42), GC_11, TMP(1))
      call CombineAmp(2,
     & (/5,2/), 
     & (/93,96/),
     & TMP, W, AMP(1,14))
      CALL FFV1P1N_2(W(1,12), W(1,43), GC_11, TMP(1))
      call CombineAmp(2,
     & (/8,4/), 
     & (/93,96/),
     & TMP, W, AMP(1,14)) ! count 1
      CALL FFV1P1N_1(W(1,1), W(1,42), GC_11, TMP(1))
      call CombineAmp(2,
     & (/17,13/), 
     & (/81,84/),
     & TMP, W, AMP(1,15))
      CALL FFV1P1N_1(W(1,1), W(1,43), GC_11, TMP(1))
      call CombineAmp(2,
     & (/19,16/), 
     & (/81,84/),
     & TMP, W, AMP(1,15))
      CALL FFV1P1N_1(W(1,2), W(1,42), GC_11, TMP(1))
      call CombineAmp(2,
     & (/5,2/), 
     & (/85,88/),
     & TMP, W, AMP(1,15))
      CALL FFV1P1N_1(W(1,2), W(1,43), GC_11, TMP(1))
      call CombineAmp(2,
     & (/8,4/), 
     & (/85,88/),
     & TMP, W, AMP(1,15)) ! count 1
      CALL FFV1P0_3(W(1,11),W(1,1),GC_11,ZERO,FK_ZERO,W(1,97)) ! count 34
      CALL FFV1P0_3(W(1,12),W(1,2),GC_11,ZERO,FK_ZERO,W(1,100)) ! count 34
      CALL VVV1P1N_1(W(1,42), W(1,97), GC_10, TMP(1))
      call CombineAmp(2,
     & (/17,13/), 
     & (/65,68/),
     & TMP, W, AMP(1,16))
      CALL VVV1P1N_1(W(1,42), W(1,100), GC_10, TMP(1))
      call CombineAmp(2,
     & (/5,2/), 
     & (/65,68/),
     & TMP, W, AMP(1,16))
      CALL VVV1P1N_1(W(1,43), W(1,97), GC_10, TMP(1))
      call CombineAmp(2,
     & (/19,16/), 
     & (/65,68/),
     & TMP, W, AMP(1,16))
      CALL VVV1P1N_1(W(1,43), W(1,100), GC_10, TMP(1))
      call CombineAmp(2,
     & (/8,4/), 
     & (/65,68/),
     & TMP, W, AMP(1,16)) ! count 1
      CALL FFV1_2(W(1,9),W(1,65),GC_11,ZERO,FK_ZERO,W(1,101)) ! count 4
      CALL FFV1_2(W(1,9),W(1,68),GC_11,ZERO,FK_ZERO,W(1,104)) ! count 4
      CALL FFV1_2(W(1,10),W(1,65),GC_11,ZERO,FK_ZERO,W(1,105)) ! count 4
      CALL FFV1_2(W(1,10),W(1,68),GC_11,ZERO,FK_ZERO,W(1,108)) ! count 4
      CALL FFV1P1N_1(W(1,6), W(1,97), GC_11, TMP(1))
      call CombineAmp(2,
     & (/17,13/), 
     & (/101,104/),
     & TMP, W, AMP(1,17))
      CALL FFV1P1N_1(W(1,6), W(1,100), GC_11, TMP(1))
      call CombineAmp(2,
     & (/5,2/), 
     & (/101,104/),
     & TMP, W, AMP(1,17))
      CALL FFV1P1N_1(W(1,5), W(1,97), GC_11, TMP(1))
      call CombineAmp(2,
     & (/19,16/), 
     & (/105,108/),
     & TMP, W, AMP(1,17))
      CALL FFV1P1N_1(W(1,5), W(1,100), GC_11, TMP(1))
      call CombineAmp(2,
     & (/8,4/), 
     & (/105,108/),
     & TMP, W, AMP(1,17)) ! count 1
      CALL FFV1P1N_2(W(1,9), W(1,97), GC_11, TMP(1))
      call CombineAmp(2,
     & (/17,13/), 
     & (/77,80/),
     & TMP, W, AMP(1,18))
      CALL FFV1P1N_2(W(1,9), W(1,100), GC_11, TMP(1))
      call CombineAmp(2,
     & (/5,2/), 
     & (/77,80/),
     & TMP, W, AMP(1,18))
      CALL FFV1P1N_2(W(1,10), W(1,97), GC_11, TMP(1))
      call CombineAmp(2,
     & (/19,16/), 
     & (/73,76/),
     & TMP, W, AMP(1,18))
      CALL FFV1P1N_2(W(1,10), W(1,100), GC_11, TMP(1))
      call CombineAmp(2,
     & (/8,4/), 
     & (/73,76/),
     & TMP, W, AMP(1,18)) ! count 1
      CALL FFV1P1N_1(W(1,1), W(1,38), GC_11, TMP(1))
      call CombineAmp(2,
     & (/17,13/), 
     & (/101,104/),
     & TMP, W, AMP(1,19))
      CALL FFV1P1N_1(W(1,1), W(1,39), GC_11, TMP(1))
      call CombineAmp(2,
     & (/18,15/), 
     & (/101,104/),
     & TMP, W, AMP(1,19))
      CALL FFV1P1N_1(W(1,2), W(1,38), GC_11, TMP(1))
      call CombineAmp(2,
     & (/6,3/), 
     & (/105,108/),
     & TMP, W, AMP(1,19))
      CALL FFV1P1N_1(W(1,2), W(1,39), GC_11, TMP(1))
      call CombineAmp(2,
     & (/8,4/), 
     & (/105,108/),
     & TMP, W, AMP(1,19)) ! count 1
      CALL FFV1P1N_2(W(1,9), W(1,38), GC_11, TMP(1))
      call CombineAmp(2,
     & (/17,13/), 
     & (/89,92/),
     & TMP, W, AMP(1,20))
      CALL FFV1P1N_2(W(1,9), W(1,39), GC_11, TMP(1))
      call CombineAmp(2,
     & (/18,15/), 
     & (/89,92/),
     & TMP, W, AMP(1,20))
      CALL FFV1P1N_2(W(1,10), W(1,38), GC_11, TMP(1))
      call CombineAmp(2,
     & (/6,3/), 
     & (/93,96/),
     & TMP, W, AMP(1,20))
      CALL FFV1P1N_2(W(1,10), W(1,39), GC_11, TMP(1))
      call CombineAmp(2,
     & (/8,4/), 
     & (/93,96/),
     & TMP, W, AMP(1,20)) ! count 1
      CALL FFV1P0_3(W(1,7),W(1,6),GC_11,ZERO,FK_ZERO,W(1,110)) ! count 16
      CALL FFV1P0_3(W(1,8),W(1,5),GC_11,ZERO,FK_ZERO,W(1,111)) ! count 16
      CALL FFV1_1(W(1,3),W(1,110),GC_11,ZERO,FK_ZERO,W(1,114)) ! count 4
      CALL FFV1_1(W(1,3),W(1,111),GC_11,ZERO,FK_ZERO,W(1,115)) ! count 4
      CALL FFV1_1(W(1,4),W(1,110),GC_11,ZERO,FK_ZERO,W(1,118)) ! count 4
      CALL FFV1_1(W(1,4),W(1,111),GC_11,ZERO,FK_ZERO,W(1,119)) ! count 4
      CALL FFV1P1N_2(W(1,11), W(1,69), GC_11, TMP(1))
      call CombineAmp(2,
     & (/17,20/), 
     & (/114,115/),
     & TMP, W, AMP(1,21))
      CALL FFV1P1N_2(W(1,11), W(1,72), GC_11, TMP(1))
      call CombineAmp(2,
     & (/6,10/), 
     & (/114,115/),
     & TMP, W, AMP(1,21))
      CALL FFV1P1N_2(W(1,12), W(1,69), GC_11, TMP(1))
      call CombineAmp(2,
     & (/11,15/), 
     & (/118,119/),
     & TMP, W, AMP(1,21))
      CALL FFV1P1N_2(W(1,12), W(1,72), GC_11, TMP(1))
      call CombineAmp(2,
     & (/1,4/), 
     & (/118,119/),
     & TMP, W, AMP(1,21)) ! count 1
      CALL FFV1_2(W(1,11),W(1,110),GC_11,ZERO,FK_ZERO,W(1,122)) ! count 4
      CALL FFV1_2(W(1,11),W(1,111),GC_11,ZERO,FK_ZERO,W(1,123)) ! count 4
      CALL FFV1_2(W(1,12),W(1,110),GC_11,ZERO,FK_ZERO,W(1,126)) ! count 4
      CALL FFV1_2(W(1,12),W(1,111),GC_11,ZERO,FK_ZERO,W(1,127)) ! count 4
      CALL FFV1P1N_1(W(1,3), W(1,69), GC_11, TMP(1))
      call CombineAmp(2,
     & (/17,20/), 
     & (/122,123/),
     & TMP, W, AMP(1,22))
      CALL FFV1P1N_1(W(1,3), W(1,72), GC_11, TMP(1))
      call CombineAmp(2,
     & (/6,10/), 
     & (/122,123/),
     & TMP, W, AMP(1,22))
      CALL FFV1P1N_1(W(1,4), W(1,69), GC_11, TMP(1))
      call CombineAmp(2,
     & (/11,15/), 
     & (/126,127/),
     & TMP, W, AMP(1,22))
      CALL FFV1P1N_1(W(1,4), W(1,72), GC_11, TMP(1))
      call CombineAmp(2,
     & (/1,4/), 
     & (/126,127/),
     & TMP, W, AMP(1,22)) ! count 1
      CALL VVV1P1N_1(W(1,69), W(1,53), GC_10, TMP(1))
      call CombineAmp(2,
     & (/17,20/), 
     & (/110,111/),
     & TMP, W, AMP(1,23))
      CALL VVV1P1N_1(W(1,69), W(1,56), GC_10, TMP(1))
      call CombineAmp(2,
     & (/11,15/), 
     & (/110,111/),
     & TMP, W, AMP(1,23))
      CALL VVV1P1N_1(W(1,72), W(1,53), GC_10, TMP(1))
      call CombineAmp(2,
     & (/6,10/), 
     & (/110,111/),
     & TMP, W, AMP(1,23))
      CALL VVV1P1N_1(W(1,72), W(1,56), GC_10, TMP(1))
      call CombineAmp(2,
     & (/1,4/), 
     & (/110,111/),
     & TMP, W, AMP(1,23)) ! count 1
      CALL FFV1_1(W(1,1),W(1,110),GC_11,ZERO,FK_ZERO,W(1,130)) ! count 4
      CALL FFV1_1(W(1,1),W(1,111),GC_11,ZERO,FK_ZERO,W(1,131)) ! count 4
      CALL FFV1_1(W(1,2),W(1,110),GC_11,ZERO,FK_ZERO,W(1,134)) ! count 4
      CALL FFV1_1(W(1,2),W(1,111),GC_11,ZERO,FK_ZERO,W(1,135)) ! count 4
      CALL FFV1P1N_2(W(1,11), W(1,17), GC_11, TMP(1))
      call CombineAmp(2,
     & (/17,20/), 
     & (/130,131/),
     & TMP, W, AMP(1,24))
      CALL FFV1P1N_2(W(1,11), W(1,20), GC_11, TMP(1))
      call CombineAmp(2,
     & (/12,16/), 
     & (/130,131/),
     & TMP, W, AMP(1,24))
      CALL FFV1P1N_2(W(1,12), W(1,17), GC_11, TMP(1))
      call CombineAmp(2,
     & (/5,9/), 
     & (/134,135/),
     & TMP, W, AMP(1,24))
      CALL FFV1P1N_2(W(1,12), W(1,20), GC_11, TMP(1))
      call CombineAmp(2,
     & (/1,4/), 
     & (/134,135/),
     & TMP, W, AMP(1,24)) ! count 1
      CALL FFV1P1N_1(W(1,1), W(1,17), GC_11, TMP(1))
      call CombineAmp(2,
     & (/17,20/), 
     & (/122,123/),
     & TMP, W, AMP(1,25))
      CALL FFV1P1N_1(W(1,1), W(1,20), GC_11, TMP(1))
      call CombineAmp(2,
     & (/12,16/), 
     & (/122,123/),
     & TMP, W, AMP(1,25))
      CALL FFV1P1N_1(W(1,2), W(1,17), GC_11, TMP(1))
      call CombineAmp(2,
     & (/5,9/), 
     & (/126,127/),
     & TMP, W, AMP(1,25))
      CALL FFV1P1N_1(W(1,2), W(1,20), GC_11, TMP(1))
      call CombineAmp(2,
     & (/1,4/), 
     & (/126,127/),
     & TMP, W, AMP(1,25)) ! count 1
      CALL VVV1P1N_1(W(1,17), W(1,97), GC_10, TMP(1))
      call CombineAmp(2,
     & (/17,20/), 
     & (/110,111/),
     & TMP, W, AMP(1,26))
      CALL VVV1P1N_1(W(1,17), W(1,100), GC_10, TMP(1))
      call CombineAmp(2,
     & (/5,9/), 
     & (/110,111/),
     & TMP, W, AMP(1,26))
      CALL VVV1P1N_1(W(1,20), W(1,97), GC_10, TMP(1))
      call CombineAmp(2,
     & (/12,16/), 
     & (/110,111/),
     & TMP, W, AMP(1,26))
      CALL VVV1P1N_1(W(1,20), W(1,100), GC_10, TMP(1))
      call CombineAmp(2,
     & (/1,4/), 
     & (/110,111/),
     & TMP, W, AMP(1,26)) ! count 1
      CALL FFV1_2(W(1,9),W(1,110),GC_11,ZERO,FK_ZERO,W(1,138)) ! count 4
      CALL FFV1_2(W(1,9),W(1,111),GC_11,ZERO,FK_ZERO,W(1,139)) ! count 4
      CALL FFV1_2(W(1,10),W(1,110),GC_11,ZERO,FK_ZERO,W(1,142)) ! count 4
      CALL FFV1_2(W(1,10),W(1,111),GC_11,ZERO,FK_ZERO,W(1,143)) ! count 4
      CALL FFV1P1N_1(W(1,3), W(1,97), GC_11, TMP(1))
      call CombineAmp(2,
     & (/17,20/), 
     & (/138,139/),
     & TMP, W, AMP(1,27))
      CALL FFV1P1N_1(W(1,3), W(1,100), GC_11, TMP(1))
      call CombineAmp(2,
     & (/5,9/), 
     & (/138,139/),
     & TMP, W, AMP(1,27))
      CALL FFV1P1N_1(W(1,4), W(1,97), GC_11, TMP(1))
      call CombineAmp(2,
     & (/12,16/), 
     & (/142,143/),
     & TMP, W, AMP(1,27))
      CALL FFV1P1N_1(W(1,4), W(1,100), GC_11, TMP(1))
      call CombineAmp(2,
     & (/1,4/), 
     & (/142,143/),
     & TMP, W, AMP(1,27)) ! count 1
      CALL FFV1P1N_2(W(1,9), W(1,97), GC_11, TMP(1))
      call CombineAmp(2,
     & (/17,20/), 
     & (/114,115/),
     & TMP, W, AMP(1,28))
      CALL FFV1P1N_2(W(1,9), W(1,100), GC_11, TMP(1))
      call CombineAmp(2,
     & (/5,9/), 
     & (/114,115/),
     & TMP, W, AMP(1,28))
      CALL FFV1P1N_2(W(1,10), W(1,97), GC_11, TMP(1))
      call CombineAmp(2,
     & (/12,16/), 
     & (/118,119/),
     & TMP, W, AMP(1,28))
      CALL FFV1P1N_2(W(1,10), W(1,100), GC_11, TMP(1))
      call CombineAmp(2,
     & (/1,4/), 
     & (/118,119/),
     & TMP, W, AMP(1,28)) ! count 1
      CALL FFV1P1N_1(W(1,1), W(1,53), GC_11, TMP(1))
      call CombineAmp(2,
     & (/17,20/), 
     & (/138,139/),
     & TMP, W, AMP(1,29))
      CALL FFV1P1N_1(W(1,1), W(1,56), GC_11, TMP(1))
      call CombineAmp(2,
     & (/11,15/), 
     & (/138,139/),
     & TMP, W, AMP(1,29))
      CALL FFV1P1N_1(W(1,2), W(1,53), GC_11, TMP(1))
      call CombineAmp(2,
     & (/6,10/), 
     & (/142,143/),
     & TMP, W, AMP(1,29))
      CALL FFV1P1N_1(W(1,2), W(1,56), GC_11, TMP(1))
      call CombineAmp(2,
     & (/1,4/), 
     & (/142,143/),
     & TMP, W, AMP(1,29)) ! count 1
      CALL FFV1P1N_2(W(1,9), W(1,53), GC_11, TMP(1))
      call CombineAmp(2,
     & (/17,20/), 
     & (/130,131/),
     & TMP, W, AMP(1,30))
      CALL FFV1P1N_2(W(1,9), W(1,56), GC_11, TMP(1))
      call CombineAmp(2,
     & (/11,15/), 
     & (/130,131/),
     & TMP, W, AMP(1,30))
      CALL FFV1P1N_2(W(1,10), W(1,53), GC_11, TMP(1))
      call CombineAmp(2,
     & (/6,10/), 
     & (/134,135/),
     & TMP, W, AMP(1,30))
      CALL FFV1P1N_2(W(1,10), W(1,56), GC_11, TMP(1))
      call CombineAmp(2,
     & (/1,4/), 
     & (/134,135/),
     & TMP, W, AMP(1,30)) ! count 1
      CALL FFV1_2(W(1,7),W(1,69),GC_11,ZERO,FK_ZERO,W(1,145)) ! count 4
      CALL FFV1_2(W(1,7),W(1,72),GC_11,ZERO,FK_ZERO,W(1,148)) ! count 4
      CALL FFV1_2(W(1,8),W(1,69),GC_11,ZERO,FK_ZERO,W(1,149)) ! count 4
      CALL FFV1_2(W(1,8),W(1,72),GC_11,ZERO,FK_ZERO,W(1,152)) ! count 4
      CALL FFV1P1N_1(W(1,6), W(1,53), GC_11, TMP(1))
      call CombineAmp(2,
     & (/17,6/), 
     & (/145,148/),
     & TMP, W, AMP(1,31))
      CALL FFV1P1N_1(W(1,6), W(1,56), GC_11, TMP(1))
      call CombineAmp(2,
     & (/11,1/), 
     & (/145,148/),
     & TMP, W, AMP(1,31))
      CALL FFV1P1N_1(W(1,5), W(1,53), GC_11, TMP(1))
      call CombineAmp(2,
     & (/20,10/), 
     & (/149,152/),
     & TMP, W, AMP(1,31))
      CALL FFV1P1N_1(W(1,5), W(1,56), GC_11, TMP(1))
      call CombineAmp(2,
     & (/15,4/), 
     & (/149,152/),
     & TMP, W, AMP(1,31)) ! count 1
      CALL FFV1_2(W(1,7),W(1,53),GC_11,ZERO,FK_ZERO,W(1,153)) ! count 4
      CALL FFV1_2(W(1,7),W(1,56),GC_11,ZERO,FK_ZERO,W(1,156)) ! count 4
      CALL FFV1_2(W(1,8),W(1,53),GC_11,ZERO,FK_ZERO,W(1,157)) ! count 4
      CALL FFV1_2(W(1,8),W(1,56),GC_11,ZERO,FK_ZERO,W(1,160)) ! count 4
      CALL FFV1P1N_1(W(1,6), W(1,69), GC_11, TMP(1))
      call CombineAmp(2,
     & (/17,11/), 
     & (/153,156/),
     & TMP, W, AMP(1,32))
      CALL FFV1P1N_1(W(1,6), W(1,72), GC_11, TMP(1))
      call CombineAmp(2,
     & (/6,1/), 
     & (/153,156/),
     & TMP, W, AMP(1,32))
      CALL FFV1P1N_1(W(1,5), W(1,69), GC_11, TMP(1))
      call CombineAmp(2,
     & (/20,15/), 
     & (/157,160/),
     & TMP, W, AMP(1,32))
      CALL FFV1P1N_1(W(1,5), W(1,72), GC_11, TMP(1))
      call CombineAmp(2,
     & (/10,4/), 
     & (/157,160/),
     & TMP, W, AMP(1,32)) ! count 1
      CALL FFV1P1N_1(W(1,3), W(1,38), GC_11, TMP(1))
      call CombineAmp(2,
     & (/17,6/), 
     & (/145,148/),
     & TMP, W, AMP(1,33))
      CALL FFV1P1N_1(W(1,3), W(1,39), GC_11, TMP(1))
      call CombineAmp(2,
     & (/18,8/), 
     & (/145,148/),
     & TMP, W, AMP(1,33))
      CALL FFV1P1N_1(W(1,4), W(1,38), GC_11, TMP(1))
      call CombineAmp(2,
     & (/13,3/), 
     & (/149,152/),
     & TMP, W, AMP(1,33))
      CALL FFV1P1N_1(W(1,4), W(1,39), GC_11, TMP(1))
      call CombineAmp(2,
     & (/15,4/), 
     & (/149,152/),
     & TMP, W, AMP(1,33)) ! count 1
      CALL FFV1_2(W(1,7),W(1,38),GC_11,ZERO,FK_ZERO,W(1,162)) ! count 4
      CALL FFV1_2(W(1,7),W(1,39),GC_11,ZERO,FK_ZERO,W(1,163)) ! count 4
      CALL FFV1_2(W(1,8),W(1,38),GC_11,ZERO,FK_ZERO,W(1,166)) ! count 4
      CALL FFV1_2(W(1,8),W(1,39),GC_11,ZERO,FK_ZERO,W(1,167)) ! count 4
      CALL FFV1P1N_1(W(1,3), W(1,69), GC_11, TMP(1))
      call CombineAmp(2,
     & (/17,18/), 
     & (/162,163/),
     & TMP, W, AMP(1,34))
      CALL FFV1P1N_1(W(1,3), W(1,72), GC_11, TMP(1))
      call CombineAmp(2,
     & (/6,8/), 
     & (/162,163/),
     & TMP, W, AMP(1,34))
      CALL FFV1P1N_1(W(1,4), W(1,69), GC_11, TMP(1))
      call CombineAmp(2,
     & (/13,15/), 
     & (/166,167/),
     & TMP, W, AMP(1,34))
      CALL FFV1P1N_1(W(1,4), W(1,72), GC_11, TMP(1))
      call CombineAmp(2,
     & (/3,4/), 
     & (/166,167/),
     & TMP, W, AMP(1,34)) ! count 1
      CALL FFV1_2(W(1,7),W(1,17),GC_11,ZERO,FK_ZERO,W(1,169)) ! count 4
      CALL FFV1_2(W(1,7),W(1,20),GC_11,ZERO,FK_ZERO,W(1,172)) ! count 4
      CALL FFV1_2(W(1,8),W(1,17),GC_11,ZERO,FK_ZERO,W(1,173)) ! count 4
      CALL FFV1_2(W(1,8),W(1,20),GC_11,ZERO,FK_ZERO,W(1,176)) ! count 4
      CALL FFV1P1N_1(W(1,6), W(1,97), GC_11, TMP(1))
      call CombineAmp(2,
     & (/17,12/), 
     & (/169,172/),
     & TMP, W, AMP(1,35))
      CALL FFV1P1N_1(W(1,6), W(1,100), GC_11, TMP(1))
      call CombineAmp(2,
     & (/5,1/), 
     & (/169,172/),
     & TMP, W, AMP(1,35))
      CALL FFV1P1N_1(W(1,5), W(1,97), GC_11, TMP(1))
      call CombineAmp(2,
     & (/20,16/), 
     & (/173,176/),
     & TMP, W, AMP(1,35))
      CALL FFV1P1N_1(W(1,5), W(1,100), GC_11, TMP(1))
      call CombineAmp(2,
     & (/9,4/), 
     & (/173,176/),
     & TMP, W, AMP(1,35)) ! count 1
      CALL FFV1_2(W(1,7),W(1,97),GC_11,ZERO,FK_ZERO,W(1,177)) ! count 4
      CALL FFV1_2(W(1,7),W(1,100),GC_11,ZERO,FK_ZERO,W(1,180)) ! count 4
      CALL FFV1_2(W(1,8),W(1,97),GC_11,ZERO,FK_ZERO,W(1,181)) ! count 4
      CALL FFV1_2(W(1,8),W(1,100),GC_11,ZERO,FK_ZERO,W(1,184)) ! count 4
      CALL FFV1P1N_1(W(1,6), W(1,17), GC_11, TMP(1))
      call CombineAmp(2,
     & (/17,5/), 
     & (/177,180/),
     & TMP, W, AMP(1,36))
      CALL FFV1P1N_1(W(1,6), W(1,20), GC_11, TMP(1))
      call CombineAmp(2,
     & (/12,1/), 
     & (/177,180/),
     & TMP, W, AMP(1,36))
      CALL FFV1P1N_1(W(1,5), W(1,17), GC_11, TMP(1))
      call CombineAmp(2,
     & (/20,9/), 
     & (/181,184/),
     & TMP, W, AMP(1,36))
      CALL FFV1P1N_1(W(1,5), W(1,20), GC_11, TMP(1))
      call CombineAmp(2,
     & (/16,4/), 
     & (/181,184/),
     & TMP, W, AMP(1,36)) ! count 1
      CALL FFV1P1N_1(W(1,1), W(1,38), GC_11, TMP(1))
      call CombineAmp(2,
     & (/17,12/), 
     & (/169,172/),
     & TMP, W, AMP(1,37))
      CALL FFV1P1N_1(W(1,1), W(1,39), GC_11, TMP(1))
      call CombineAmp(2,
     & (/18,14/), 
     & (/169,172/),
     & TMP, W, AMP(1,37))
      CALL FFV1P1N_1(W(1,2), W(1,38), GC_11, TMP(1))
      call CombineAmp(2,
     & (/7,3/), 
     & (/173,176/),
     & TMP, W, AMP(1,37))
      CALL FFV1P1N_1(W(1,2), W(1,39), GC_11, TMP(1))
      call CombineAmp(2,
     & (/9,4/), 
     & (/173,176/),
     & TMP, W, AMP(1,37)) ! count 1
      CALL FFV1P1N_1(W(1,1), W(1,17), GC_11, TMP(1))
      call CombineAmp(2,
     & (/17,18/), 
     & (/162,163/),
     & TMP, W, AMP(1,38))
      CALL FFV1P1N_1(W(1,1), W(1,20), GC_11, TMP(1))
      call CombineAmp(2,
     & (/12,14/), 
     & (/162,163/),
     & TMP, W, AMP(1,38))
      CALL FFV1P1N_1(W(1,2), W(1,17), GC_11, TMP(1))
      call CombineAmp(2,
     & (/7,9/), 
     & (/166,167/),
     & TMP, W, AMP(1,38))
      CALL FFV1P1N_1(W(1,2), W(1,20), GC_11, TMP(1))
      call CombineAmp(2,
     & (/3,4/), 
     & (/166,167/),
     & TMP, W, AMP(1,38)) ! count 1
      CALL FFV1_2(W(1,7),W(1,42),GC_11,ZERO,FK_ZERO,W(1,186)) ! count 4
      CALL FFV1_2(W(1,7),W(1,43),GC_11,ZERO,FK_ZERO,W(1,187)) ! count 4
      CALL FFV1_2(W(1,8),W(1,42),GC_11,ZERO,FK_ZERO,W(1,190)) ! count 4
      CALL FFV1_2(W(1,8),W(1,43),GC_11,ZERO,FK_ZERO,W(1,191)) ! count 4
      CALL FFV1P1N_1(W(1,3), W(1,97), GC_11, TMP(1))
      call CombineAmp(2,
     & (/17,19/), 
     & (/186,187/),
     & TMP, W, AMP(1,39))
      CALL FFV1P1N_1(W(1,3), W(1,100), GC_11, TMP(1))
      call CombineAmp(2,
     & (/5,8/), 
     & (/186,187/),
     & TMP, W, AMP(1,39))
      CALL FFV1P1N_1(W(1,4), W(1,97), GC_11, TMP(1))
      call CombineAmp(2,
     & (/13,16/), 
     & (/190,191/),
     & TMP, W, AMP(1,39))
      CALL FFV1P1N_1(W(1,4), W(1,100), GC_11, TMP(1))
      call CombineAmp(2,
     & (/2,4/), 
     & (/190,191/),
     & TMP, W, AMP(1,39)) ! count 1
      CALL FFV1P1N_1(W(1,3), W(1,42), GC_11, TMP(1))
      call CombineAmp(2,
     & (/17,5/), 
     & (/177,180/),
     & TMP, W, AMP(1,40))
      CALL FFV1P1N_1(W(1,3), W(1,43), GC_11, TMP(1))
      call CombineAmp(2,
     & (/19,8/), 
     & (/177,180/),
     & TMP, W, AMP(1,40))
      CALL FFV1P1N_1(W(1,4), W(1,42), GC_11, TMP(1))
      call CombineAmp(2,
     & (/13,2/), 
     & (/181,184/),
     & TMP, W, AMP(1,40))
      CALL FFV1P1N_1(W(1,4), W(1,43), GC_11, TMP(1))
      call CombineAmp(2,
     & (/16,4/), 
     & (/181,184/),
     & TMP, W, AMP(1,40)) ! count 1
      CALL FFV1P1N_1(W(1,1), W(1,53), GC_11, TMP(1))
      call CombineAmp(2,
     & (/17,19/), 
     & (/186,187/),
     & TMP, W, AMP(1,41))
      CALL FFV1P1N_1(W(1,1), W(1,56), GC_11, TMP(1))
      call CombineAmp(2,
     & (/11,14/), 
     & (/186,187/),
     & TMP, W, AMP(1,41))
      CALL FFV1P1N_1(W(1,2), W(1,53), GC_11, TMP(1))
      call CombineAmp(2,
     & (/7,10/), 
     & (/190,191/),
     & TMP, W, AMP(1,41))
      CALL FFV1P1N_1(W(1,2), W(1,56), GC_11, TMP(1))
      call CombineAmp(2,
     & (/2,4/), 
     & (/190,191/),
     & TMP, W, AMP(1,41)) ! count 1
      CALL FFV1P1N_1(W(1,1), W(1,42), GC_11, TMP(1))
      call CombineAmp(2,
     & (/17,11/), 
     & (/153,156/),
     & TMP, W, AMP(1,42))
      CALL FFV1P1N_1(W(1,1), W(1,43), GC_11, TMP(1))
      call CombineAmp(2,
     & (/19,14/), 
     & (/153,156/),
     & TMP, W, AMP(1,42))
      CALL FFV1P1N_1(W(1,2), W(1,42), GC_11, TMP(1))
      call CombineAmp(2,
     & (/7,2/), 
     & (/157,160/),
     & TMP, W, AMP(1,42))
      CALL FFV1P1N_1(W(1,2), W(1,43), GC_11, TMP(1))
      call CombineAmp(2,
     & (/10,4/), 
     & (/157,160/),
     & TMP, W, AMP(1,42)) ! count 1

      JAMP(:,:)  = (0d0,0d0)
      DO K = 1, NCOMB
        
        JAMP(:,:) = (0D0,0D0)
C       JAMPs contributing to orders ALL_ORDERS=1
        TMP_JAMP(38) = AMP( K,39) +  AMP( K,40)  ! used 3 times
        TMP_JAMP(37) = AMP( K,37) +  AMP( K,38)  ! used 3 times
        TMP_JAMP(36) = AMP( K,35) +  AMP( K,36)  ! used 3 times
        TMP_JAMP(35) = AMP( K,30) +  AMP( K,40)  ! used 3 times
        TMP_JAMP(34) = AMP( K,29) +  AMP( K,30)  ! used 3 times
        TMP_JAMP(33) = AMP( K,27) +  AMP( K,36)  ! used 3 times
        TMP_JAMP(32) = AMP( K,27) +  AMP( K,28)  ! used 3 times
        TMP_JAMP(31) = AMP( K,25) +  AMP( K,35)  ! used 3 times
        TMP_JAMP(30) = AMP( K,24) +  AMP( K,36)  ! used 3 times
        TMP_JAMP(29) = AMP( K,24) +  AMP( K,25)  ! used 3 times
        TMP_JAMP(28) = AMP( K,21) +  AMP( K,22)  ! used 3 times
        TMP_JAMP(27) = AMP( K,19) +  AMP( K,34)  ! used 3 times
        TMP_JAMP(26) = AMP( K,17) +  AMP( K,22)  ! used 3 times
        TMP_JAMP(25) = AMP( K,17) +  AMP( K,18)  ! used 3 times
        TMP_JAMP(24) = AMP( K,11) +  AMP( K,34)  ! used 3 times
        TMP_JAMP(23) = AMP( K,11) +  AMP( K,19)  ! used 3 times
        TMP_JAMP(22) = AMP( K,5) +  AMP( K,8)  ! used 3 times
        TMP_JAMP(21) = AMP( K,1) +  AMP( K,2)  ! used 3 times
        TMP_JAMP(20) = AMP( K,41) +  AMP( K,42)  ! used 3 times
        TMP_JAMP(19) = AMP( K,29) +  AMP( K,32)  ! used 3 times
        TMP_JAMP(18) = AMP( K,28) +  AMP( K,42)  ! used 3 times
        TMP_JAMP(17) = AMP( K,21) +  AMP( K,32)  ! used 3 times
        TMP_JAMP(16) = AMP( K,19) +  AMP( K,20)  ! used 3 times
        TMP_JAMP(15) = AMP( K,15) +  AMP( K,39)  ! used 3 times
        TMP_JAMP(14) = AMP( K,15) +  AMP( K,18)  ! used 3 times
        TMP_JAMP(13) = AMP( K,14) +  AMP( K,15)  ! used 3 times
        TMP_JAMP(12) = AMP( K,12) +  AMP( K,27)  ! used 3 times
        TMP_JAMP(11) = AMP( K,11) +  AMP( K,12)  ! used 3 times
        TMP_JAMP(10) = AMP( K,4) +  AMP( K,5)  ! used 3 times
        TMP_JAMP(9) = AMP( K,2) +  AMP( K,10)  ! used 3 times
        TMP_JAMP(8) = AMP( K,22) +  AMP( K,31)  ! used 3 times
        TMP_JAMP(7) = AMP( K,12) +  AMP( K,33)  ! used 3 times
        TMP_JAMP(6) = AMP( K,7) +  AMP( K,8)  ! used 3 times
        TMP_JAMP(5) = AMP( K,1) +  AMP( K,9)  ! used 3 times
        TMP_JAMP(4) = AMP( K,20) +  AMP( K,33)  ! used 3 times
        TMP_JAMP(3) = AMP( K,14) +  AMP( K,31)  ! used 3 times
        TMP_JAMP(2) = AMP( K,9) +  AMP( K,10)  ! used 3 times
        TMP_JAMP(1) = AMP( K,4) +  AMP( K,7)  ! used 3 times
        TMP_JAMP(51) = TMP_JAMP(34) + (3.000000000000000D+00) * AMP( K,4
     $  1)  ! used 2 times
        TMP_JAMP(50) = TMP_JAMP(36) +  TMP_JAMP(29)  ! used 2 times
        TMP_JAMP(49) = TMP_JAMP(37) + (3.000000000000000D+00) *  TMP_JAM
     $  P(22)  ! used 2 times
        TMP_JAMP(48) = TMP_JAMP(38) +  TMP_JAMP(25)  ! used 2 times
        TMP_JAMP(47) = TMP_JAMP(17) + (3.333333333333333D-01) *  TMP_JAM
     $  P(11)  ! used 2 times
        TMP_JAMP(46) = TMP_JAMP(18) +  AMP( K,41)  ! used 2 times
        TMP_JAMP(45) = TMP_JAMP(18) + (3.333333333333333D-01) *  TMP_JAM
     $  P(17)  ! used 2 times
        TMP_JAMP(44) = TMP_JAMP(4) + (3.000000000000000D+00) *  TMP_JAMP
     $  (3)  ! used 2 times
        TMP_JAMP(43) = TMP_JAMP(27) + (3.000000000000000D+00) *  TMP_JAM
     $  P(26)  ! used 2 times
        TMP_JAMP(42) = TMP_JAMP(37) +  TMP_JAMP(2)  ! used 2 times
        TMP_JAMP(41) = TMP_JAMP(3) + (3.333333333333333D-01) *  TMP_JAMP
     $  (1)  ! used 2 times
        TMP_JAMP(40) = TMP_JAMP(21) + (3.000000000000000D+00) *  TMP_JAM
     $  P(4)  ! used 2 times
        TMP_JAMP(39) = TMP_JAMP(35) + (3.333333333333333D-01) *  TMP_JAM
     $  P(22)  ! used 2 times
        TMP_JAMP(52) = TMP_JAMP(41) +  TMP_JAMP(39)  ! used 2 times
        JAMP(1,1) = ((0.000000000000000D+00,-2.500000000000000D-01)) *AM
     $  P( K,16)+((0.000000000000000D+00,2.500000000000000D-01))*AMP( K,23) +(2.
     $  777777777777778D-02)*TMP_JAMP(40)+(2.777777777777778D-02) *TMP_JAMP(42)+
     $  (8.333333333333333D-02)*TMP_JAMP(43) +(8.333333333333333D-02)*TMP_JAMP(5
     $  0)+(2.500000000000000D-01) *TMP_JAMP(52)
        JAMP(2,1) = ((0.000000000000000D+00,-2.500000000000000D-01)) *AM
     $  P( K,13)+((0.000000000000000D+00,2.500000000000000D-01))*AMP( K,26) +(-8
     $  .333333333333333D-02)*TMP_JAMP(2)+(-2.500000000000000D-01) *TMP_JAMP(12)
     $  +(-8.333333333333333D-02)*TMP_JAMP(15)+( -8.333333333333333D-02)*TMP_JAM
     $  P(19)+(-2.777777777777778D-02) *TMP_JAMP(20)+(-2.500000000000000D-01)*TM
     $  P_JAMP(30)+( -8.333333333333333D-02)*TMP_JAMP(40)+(-8.333333333333333D-0
     $  2) *TMP_JAMP(52)
        JAMP(3,1) = ((0.000000000000000D+00,2.500000000000000D-01)) *AMP
     $  ( K,6)+((0.000000000000000D+00,-2.500000000000000D-01))*AMP( K,26) +(-2.
     $  500000000000000D-01)*TMP_JAMP(1)+(-2.777777777777778D-02) *TMP_JAMP(11)+
     $  (-8.333333333333333D-02)*TMP_JAMP(14)+( -2.500000000000000D-01)*TMP_JAMP
     $  (31)+(-8.333333333333333D-02) *TMP_JAMP(42)+(-2.777777777777778D-02)*TMP
     $  _JAMP(43)+( -2.777777777777778D-02)*TMP_JAMP(44)+(-2.500000000000000D-01
     $  ) *TMP_JAMP(45)
        JAMP(4,1) = ((0.000000000000000D+00,-2.500000000000000D-01)) *AM
     $  P( K,3)+((0.000000000000000D+00,2.500000000000000D-01))*AMP( K,16) +(8.3
     $  33333333333333D-02)*AMP( K,27)+(2.500000000000000D-01)*AMP( K,38) +(2.50
     $  0000000000000D-01)*AMP( K,39)+(2.500000000000000D-01) *TMP_JAMP(5)+(8.33
     $  3333333333333D-02)*TMP_JAMP(6) +(8.333333333333333D-02)*TMP_JAMP(7)+(2.7
     $  77777777777778D-02) *TMP_JAMP(8)+(2.500000000000000D-01)*TMP_JAMP(14) +(
     $  8.333333333333333D-02)*TMP_JAMP(24)+(8.333333333333333D-02) *TMP_JAMP(29
     $  )+(8.333333333333333D-02)*TMP_JAMP(45) +(2.777777777777778D-02)*TMP_JAMP
     $  (51)
        JAMP(5,1) = ((0.000000000000000D+00,2.500000000000000D-01)) *AMP
     $  ( K,3)+((0.000000000000000D+00,-2.500000000000000D-01))*AMP( K,23) +(2.5
     $  00000000000000D-01)*AMP( K,29)+(8.333333333333333D-02)*AMP( K,35) +(2.50
     $  0000000000000D-01)*AMP( K,37)+(2.500000000000000D-01) *TMP_JAMP(9)+(8.33
     $  3333333333333D-02)*TMP_JAMP(10) +(2.777777777777778D-02)*TMP_JAMP(13)+(8
     $  .333333333333333D-02) *TMP_JAMP(16)+(8.333333333333333D-02)*TMP_JAMP(33)
     $   +(8.333333333333333D-02)*TMP_JAMP(46)+(2.500000000000000D-01) *TMP_JAMP
     $  (47)+(2.777777777777778D-02)*TMP_JAMP(48)
        JAMP(6,1) = ((0.000000000000000D+00,-2.500000000000000D-01)) *AM
     $  P( K,6)+((0.000000000000000D+00,2.500000000000000D-01))*AMP( K,13) +(-2.
     $  500000000000000D-01)*AMP( K,34)+(-8.333333333333333D-02) *TMP_JAMP(21)+(
     $  -2.500000000000000D-01)*TMP_JAMP(23)+( -8.333333333333333D-02)*TMP_JAMP(
     $  28)+(-2.777777777777778D-02) *TMP_JAMP(32)+(-8.333333333333333D-02)*TMP_
     $  JAMP(48)+( -8.333333333333333D-02)*TMP_JAMP(49)+(-2.777777777777778D-02)
     $   *TMP_JAMP(50)+(-8.333333333333333D-02)*TMP_JAMP(51)

        TS(K) = 0.D0 
        DO M = 1, NAMPSO
          DO I = 1, NCOLOR
            ZTEMP = (0.D0,0.D0)
            DO J = 1, NCOLOR
              ZTEMP = ZTEMP + CF(J,I)*JAMP(J,M)
            ENDDO
            DO N = 1, NAMPSO

              TS(K) = TS(K) + ZTEMP*DCONJG(JAMP(I,N))

            ENDDO
          ENDDO
        ENDDO
        if(sde_strat.eq.1) then
        
        IF(SDE_STRAT.EQ.1)THEN
          AMP2(1)=AMP2(1)+AMP( K,1)*DCONJG(AMP( K,1))
          AMP2(2)=AMP2(2)+AMP( K,2)*DCONJG(AMP( K,2))
          AMP2(3)=AMP2(3)+AMP( K,3)*DCONJG(AMP( K,3))
          AMP2(10)=AMP2(10)+AMP( K,10)*DCONJG(AMP( K,10))
          AMP2(9)=AMP2(9)+AMP( K,9)*DCONJG(AMP( K,9))
          AMP2(12)=AMP2(12)+AMP( K,12)*DCONJG(AMP( K,12))
          AMP2(11)=AMP2(11)+AMP( K,11)*DCONJG(AMP( K,11))
          AMP2(13)=AMP2(13)+AMP( K,13)*DCONJG(AMP( K,13))
          AMP2(34)=AMP2(34)+AMP( K,34)*DCONJG(AMP( K,34))
          AMP2(33)=AMP2(33)+AMP( K,33)*DCONJG(AMP( K,33))
          AMP2(20)=AMP2(20)+AMP( K,20)*DCONJG(AMP( K,20))
          AMP2(19)=AMP2(19)+AMP( K,19)*DCONJG(AMP( K,19))
          AMP2(38)=AMP2(38)+AMP( K,38)*DCONJG(AMP( K,38))
          AMP2(37)=AMP2(37)+AMP( K,37)*DCONJG(AMP( K,37))
          AMP2(4)=AMP2(4)+AMP( K,4)*DCONJG(AMP( K,4))
          AMP2(5)=AMP2(5)+AMP( K,5)*DCONJG(AMP( K,5))
          AMP2(6)=AMP2(6)+AMP( K,6)*DCONJG(AMP( K,6))
          AMP2(7)=AMP2(7)+AMP( K,7)*DCONJG(AMP( K,7))
          AMP2(8)=AMP2(8)+AMP( K,8)*DCONJG(AMP( K,8))
          AMP2(42)=AMP2(42)+AMP( K,42)*DCONJG(AMP( K,42))
          AMP2(41)=AMP2(41)+AMP( K,41)*DCONJG(AMP( K,41))
          AMP2(14)=AMP2(14)+AMP( K,14)*DCONJG(AMP( K,14))
          AMP2(15)=AMP2(15)+AMP( K,15)*DCONJG(AMP( K,15))
          AMP2(16)=AMP2(16)+AMP( K,16)*DCONJG(AMP( K,16))
          AMP2(17)=AMP2(17)+AMP( K,17)*DCONJG(AMP( K,17))
          AMP2(18)=AMP2(18)+AMP( K,18)*DCONJG(AMP( K,18))
          AMP2(21)=AMP2(21)+AMP( K,21)*DCONJG(AMP( K,21))
          AMP2(22)=AMP2(22)+AMP( K,22)*DCONJG(AMP( K,22))
          AMP2(23)=AMP2(23)+AMP( K,23)*DCONJG(AMP( K,23))
          AMP2(24)=AMP2(24)+AMP( K,24)*DCONJG(AMP( K,24))
          AMP2(25)=AMP2(25)+AMP( K,25)*DCONJG(AMP( K,25))
          AMP2(26)=AMP2(26)+AMP( K,26)*DCONJG(AMP( K,26))
          AMP2(27)=AMP2(27)+AMP( K,27)*DCONJG(AMP( K,27))
          AMP2(28)=AMP2(28)+AMP( K,28)*DCONJG(AMP( K,28))
          AMP2(29)=AMP2(29)+AMP( K,29)*DCONJG(AMP( K,29))
          AMP2(30)=AMP2(30)+AMP( K,30)*DCONJG(AMP( K,30))
          AMP2(31)=AMP2(31)+AMP( K,31)*DCONJG(AMP( K,31))
          AMP2(32)=AMP2(32)+AMP( K,32)*DCONJG(AMP( K,32))
          AMP2(35)=AMP2(35)+AMP( K,35)*DCONJG(AMP( K,35))
          AMP2(36)=AMP2(36)+AMP( K,36)*DCONJG(AMP( K,36))
          AMP2(39)=AMP2(39)+AMP( K,39)*DCONJG(AMP( K,39))
          AMP2(40)=AMP2(40)+AMP( K,40)*DCONJG(AMP( K,40))
        ENDIF

        endif
        Do I = 1, NCOLOR
          DO M = 1, NAMPSO
            DO N = 1, NAMPSO

              Jamp2(i)=Jamp2(i)+DABS(DBLE(Jamp(i,m)*dconjg(Jamp(i,n))))

            enddo
          enddo
        Enddo
      ENDDO

      END


      SUBROUTINE PRINT_ZERO_AMP_3()

      integer i
      i =1
      return
      end
C     Set of functions to handle the array indices of the split orders


      INTEGER FUNCTION SQSOINDEX3(ORDERINDEXA, ORDERINDEXB)
C     
C     This functions plays the role of the interference matrix. It can
C      be hardcoded or 
C     made more elegant using hashtables if its execution speed ever
C      becomes a relevant
C     factor. From two split order indices, it return the
C      corresponding index in the squared 
C     order canonical ordering.
C     
C     CONSTANTS
C     

      INTEGER    NSO, NSQUAREDSO, NAMPSO
      PARAMETER (NSO=1, NSQUAREDSO=1, NAMPSO=1)
C     
C     ARGUMENTS
C     
      INTEGER ORDERINDEXA, ORDERINDEXB
C     
C     LOCAL VARIABLES
C     
      INTEGER I, SQORDERS(NSO)
      INTEGER AMPSPLITORDERS(NAMPSO,NSO)
      DATA (AMPSPLITORDERS(  1,i),i=  1,  1) /    1/
      COMMON/AMPSPLITORDERS3/AMPSPLITORDERS
C     
C     FUNCTION
C     
      INTEGER SOINDEX_FOR_SQUARED_ORDERS3
C     
C     BEGIN CODE
C     
      DO I=1,NSO
        SQORDERS(I)=AMPSPLITORDERS(ORDERINDEXA,I)
     $   +AMPSPLITORDERS(ORDERINDEXB,I)
      ENDDO
      SQSOINDEX3=SOINDEX_FOR_SQUARED_ORDERS3(SQORDERS)
      END

      INTEGER FUNCTION SOINDEX_FOR_SQUARED_ORDERS3(ORDERS)
C     
C     This functions returns the integer index identifying the squared
C      split orders list passed in argument which corresponds to the
C      values of the following list of couplings (and in this order).
C     []
C     
C     CONSTANTS
C     
      INTEGER    NSO, NSQSO, NAMPSO
      PARAMETER (NSO=1, NSQSO=1, NAMPSO=1)
C     
C     ARGUMENTS
C     
      INTEGER ORDERS(NSO)
C     
C     LOCAL VARIABLES
C     
      INTEGER I,J
      INTEGER SQSPLITORDERS(NSQSO,NSO)
      DATA (SQSPLITORDERS(  1,i),i=  1,  1) /    2/
      COMMON/SQPLITORDERS3/SQPLITORDERS
C     
C     BEGIN CODE
C     
      DO I=1,NSQSO
        DO J=1,NSO
          IF (ORDERS(J).NE.SQSPLITORDERS(I,J)) GOTO 1009
        ENDDO
        SOINDEX_FOR_SQUARED_ORDERS3 = I
        RETURN
 1009   CONTINUE
      ENDDO

      WRITE(*,*) 'ERROR:: Stopping in function' 
      WRITE(*,*) 'SOINDEX_FOR_SQUARED_ORDERS3'
      WRITE(*,*) 'Could not find squared orders ',(ORDERS(I),I=1,NSO)
      STOP

      END

      SUBROUTINE GET_NSQSO_BORN3(NSQSO)
C     
C     Simple subroutine returning the number of squared split order
C     contributions returned when calling smatrix_split_orders 
C     

      INTEGER    NSQUAREDSO
      PARAMETER  (NSQUAREDSO=1)

      INTEGER NSQSO

      NSQSO=NSQUAREDSO

      END

C     This is the inverse subroutine of SOINDEX_FOR_SQUARED_ORDERS.
C      Not directly useful, but provided nonetheless.
      SUBROUTINE GET_SQUARED_ORDERS_FOR_SOINDEX3(SOINDEX,ORDERS)
C     
C     This functions returns the orders identified by the squared
C      split order index in argument. Order values correspond to
C      following list of couplings (and in this order):
C     []
C     
C     CONSTANTS
C     
      INTEGER    NSO, NSQSO
      PARAMETER (NSO=1, NSQSO=1)
C     
C     ARGUMENTS
C     
      INTEGER SOINDEX, ORDERS(NSO)
C     
C     LOCAL VARIABLES
C     
      INTEGER I
      INTEGER SQPLITORDERS(NSQSO,NSO)
      COMMON/SQPLITORDERS3/SQPLITORDERS	  
C     
C     BEGIN CODE
C     
      IF (SOINDEX.gt.0.and.SOINDEX.le.NSQSO) THEN
        DO I=1,NSO
          ORDERS(I) =  SQPLITORDERS(SOINDEX,I)
        ENDDO
        RETURN
      ENDIF

      WRITE(*,*) 'ERROR:: Stopping function'
     $ //' GET_SQUARED_ORDERS_FOR_SOINDEX3'
      WRITE(*,*) 'Could not find squared orders index ',SOINDEX
      STOP

      END SUBROUTINE

C     This is the inverse subroutine of getting amplitude SO orders.
C      Not directly useful, but provided nonetheless.
      SUBROUTINE GET_ORDERS_FOR_AMPSOINDEX3(SOINDEX,ORDERS)
C     
C     This functions returns the orders identified by the split order
C      index in argument. Order values correspond to following list of
C      couplings (and in this order):
C     []
C     
C     CONSTANTS
C     
      INTEGER    NSO, NAMPSO
      PARAMETER (NSO=1, NAMPSO=1)
C     
C     ARGUMENTS
C     
      INTEGER SOINDEX, ORDERS(NSO)
C     
C     LOCAL VARIABLES
C     
      INTEGER I
      INTEGER AMPSPLITORDERS(NAMPSO,NSO)
      COMMON/AMPSPLITORDERS3/AMPSPLITORDERS
C     
C     BEGIN CODE
C     
      IF (SOINDEX.gt.0.and.SOINDEX.le.NAMPSO) THEN
        DO I=1,NSO
          ORDERS(I) =  AMPSPLITORDERS(SOINDEX,I)
        ENDDO
        RETURN
      ENDIF

      WRITE(*,*) 'ERROR:: Stopping function GET_ORDERS_FOR_AMPSOINDEX3'
      WRITE(*,*) 'Could not find amplitude split orders index ',SOINDEX
      STOP

      END SUBROUTINE

C     This function is not directly useful, but included for
C      completeness
      INTEGER FUNCTION SOINDEX_FOR_AMPORDERS3(ORDERS)
C     
C     This functions returns the integer index identifying the
C      amplitude split orders passed in argument which correspond to
C      the values of the following list of couplings (and in this
C      order):
C     []
C     
C     CONSTANTS
C     
      INTEGER    NSO, NAMPSO
      PARAMETER (NSO=1, NAMPSO=1)
C     
C     ARGUMENTS
C     
      INTEGER ORDERS(NSO)
C     
C     LOCAL VARIABLES
C     
      INTEGER I,J
      INTEGER AMPSPLITORDERS(NAMPSO,NSO)
      COMMON/AMPSPLITORDERS3/AMPSPLITORDERS
C     
C     BEGIN CODE
C     
      DO I=1,NAMPSO
        DO J=1,NSO
          IF (ORDERS(J).NE.AMPSPLITORDERS(I,J)) GOTO 1009
        ENDDO
        SOINDEX_FOR_AMPORDERS3 = I
        RETURN
 1009   CONTINUE
      ENDDO

      WRITE(*,*) 'ERROR:: Stopping function SOINDEX_FOR_AMPORDERS3'
      WRITE(*,*) 'Could not find squared orders ',(ORDERS(I),I=1,NSO)
      STOP

      END

